# Generated by Django 6.0.7 on 2026-07-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='Format: YYYY-MM', max_length=7, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_months', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
