# Generated by Django 6.0.7 on 2026-07-28 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_client_contact_client_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent_project',
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Date project is delivered/completed. AMC starts 3 months after.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 15.00 for 15%', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancements', to='finance.project')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Domain & Server 2026', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='finance.project')),
            ],
        ),
    ]
