# Generated by Django 6.0.7 on 2026-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_project_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancement',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
