# Generated by Django 5.2.4 on 2026-07-30 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_advancewallet_id_alter_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for deposits, negative for withdrawals', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INVOICE_PAYMENT', 'Invoice Payment'), ('EXPENSE_PAYMENT', 'Expense Payment'), ('WALLET_SETTLEMENT', 'Wallet Settlement'), ('TRANSFER_IN', 'Internal Transfer (In)'), ('TRANSFER_OUT', 'Internal Transfer (Out)'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankaccount')),
            ],
        ),
    ]
