# Generated by Django 5.2.4 on 2026-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ACCOUNTANT', 'Accountant')], default='OWNER', max_length=20),
        ),
    ]
