# Generated by Django 5.2.4 on 2026-07-30 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to=settings.AUTH_USER_MODEL)),
                ('source_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_advances', to='finance.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('DIRECT', 'Direct Expense (Company Bank Account)'), ('FROM_WALLET', 'Paid from Owner Wallet')], max_length=20)),
                ('payee_description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('SERVERS', 'Servers / Hosting'), ('SOFTWARE', 'Software Licenses'), ('MARKETING', 'Marketing'), ('OFFICE', 'Office Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.project')),
                ('withdrawal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.bankaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
