# Generated by Django 6.0.5 on 2026-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_advancerequest_id_alter_advancewallet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexpense',
            name='receipt_file',
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='receipt_drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
