# Generated by Django 6.0.5 on 2026-08-27 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_companyexpense_receipt_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INVOICE_PAYMENT', 'Invoice Payment'), ('EXPENSE_PAYMENT', 'Expense Payment'), ('WALLET_SETTLEMENT', 'Wallet Settlement'), ('TRANSFER_IN', 'Internal Transfer (In)'), ('TRANSFER_OUT', 'Internal Transfer (Out)'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('OWNER_DRAW', 'Owner Draw')], max_length=25),
        ),
        migrations.CreateModel(
            name='OwnerDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drawings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
                ('source_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_drawings', to='finance.bankaccount')),
            ],
        ),
    ]
