# Generated by Django 6.0.5 on 2026-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_transaction_type_ownerdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='IN-TA SOLUTION PVT LTD', max_length=255)),
                ('address', models.TextField(default='123 Tech Park, Suite 400\nBusiness District, 10001')),
                ('contact_email', models.CharField(default='contact@intasolutions.com', max_length=255)),
                ('bank_info', models.TextField(default='Payment is due within 15 days.\nPlease make checks payable to\nIN-TA SOLUTION PVT LTD.')),
                ('payment_info', models.TextField(default='<b>Payment Info:</b><br/>A/C Name: IN-TA SOLUTION PVT LTD<br/>Bank: Standard Bank<br/>A/C No: 1234 5678 9012')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
        ),
    ]
