# Generated by Django 6.0.5 on 2026-08-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_companyprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
