# Generated by Django 6.0.5 on 2026-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_delete_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, help_text='Custom description for the invoice line item', max_length=255, null=True),
        ),
    ]
