# Generated by Django 6.0.5 on 2026-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('PARTIAL', 'Partial Payment'), ('ADVANCE', 'Advance Payment'), ('FULL', 'Full Payment'), ('RENEWAL', 'Renewal / AMC')], default='PARTIAL', max_length=20),
        ),
    ]
