# Generated by Django 6.0.5 on 2026-08-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_invoice_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancerequest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='advancewallet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='companyexpense',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='enhancement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='monthlock',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ownerdraw',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='renewal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
