# Generated by Django 6.0.5 on 2026-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_advancerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='revenue_share_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total profit pool for the month (USD/INR)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_share_seats_sold',
            field=models.IntegerField(blank=True, help_text='Number of seats sold', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='per_seat_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of 1 seat/admission in USD or INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue_share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 20.00 for 20%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue_share_type',
            field=models.CharField(blank=True, choices=[('PROFIT_SHARE', 'Monthly Profit Share'), ('PER_SEAT', 'Per Seat / Admission Share')], max_length=20, null=True),
        ),
    ]
