# Generated by Django 6.0.5 on 2026-08-28 11:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_invoice_revenue_share_base_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueShareScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. MBBS, Nursing', max_length=255)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per seat or target cost', max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share_scopes', to='finance.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_share_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.revenuesharescope'),
        ),
    ]
