# Generated by Django 6.0.5 on 2026-09-01 05:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_revenuesharescope_invoice_revenue_share_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuesharescope',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='revenuesharescope',
            name='share_percentage',
        ),
        migrations.AddField(
            model_name='revenuesharescope',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat earning per seat in USD', max_digits=12),
        ),
    ]
